title: "Tech Blog"
description: >- # this means to ignore newlines until "baseurl:"
  Just my two cents.
baseurl: ""
url: "https://nati.technology"
#twitter_username: SegmentSamba

# Build settings
theme: minima
plugins:
  - jekyll-feed
